### PR TITLE
Fixed event search box directing to eventyay common event listing

### LINKED ISSUE #516: Eventyay Common: Event search box should direct to eventyay common event listing
Currently the event search box on eventyay-common directs the event listing on eventyay tickets. Expected is that the search box events direct to the listing of eventyay common.

Image

### PR DESCRIPTION
**Pull request by suhailnadaf509**
I've made the following changes to implement the event search functionality that directs to eventyay common instead of eventyay tickets:

1) Created a new JavaScript file dashboard.js that implements the typeahead search functionality using the eventyay common URLs
2) Added a new EventSearchView that handles the search API endpoint
3) Added a URL pattern for the search endpoint
4) Updated the dashboard template to use our new JavaScript implementation and removed the old typeahead implementation

Closes #516

## Summary by Sourcery

New Features:
- Adds an event search functionality to the dashboard.

### CODE REVIEW

File: src/pretix/eventyay_common/static/eventyay-common/js/ui/dashboard.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+      hint: true,
+      highlight: true,
+      minLength: 1,
+    },
+    {
+      name: "events",
+      display: "name",
+      source: eventSearch,
+      templates: {
+        suggestion: function (data) {
```
[the remark this answers is not in the document]
Comment (suhailnadaf509) [reply src/pretix/eventyay_common/static/eventyay-common/js/ui/dashboard.js:26]: I've updated the dashboard.js file to use the ES6 template

File: src/pretix/base/orderimport.py [hunk 2]
```diff
@@ -542,7 +542,7 @@ def __init__(self, *args):
         super().__init__(*args)
 
     def clean(self, value, previous_values):
-        if value and (value in self._cached or OrderPosition.all.filter(order__event__organizer=self.event.organizer, secret=value).exists()):
+                if value and (value in self._cached or OrderPosition.all.filter(order__event__organizer=self.event.organizer, secret=value).exists()):
             raise ValidationError(
```
Comment (Sak1012) [inline src/pretix/base/orderimport.py]: The docker build fails due to an Indentation Error here, please fix that

**Comment by mariobehling** [comment]
Please help to get Docker working.

File: src/pretix/base/orderimport.py (hunk 2 above)
Comment (norbusan) [reply src/pretix/base/orderimport.py]: @suhailnadaf509 I fixed the indentation, please check whether the rest of the function is correctly indented.

File: src/pretix/eventyay_common/templates/eventyay_common/dashboard/dashboard.html [hunk 3]
```diff
@@ -1,130 +1,45 @@
...
+trans "Dashboard" %} {% endblock %} {% block content %}
+<h1>{% trans "Dashboard" %}</h1>
+<div class="dropdown-container">
+  <input
+    type="text"
+    class="form-control"
+    id="dashboard_query"
+    placeholder="{% trans 'Go to event' %}"
+    autofocus
+  />
```
Comment (norbusan) [inline src/pretix/eventyay_common/templates/eventyay_common/dashboard/dashboard.html]: Please keep the original formatting as far as possible. The code above is the same as in the original file, just reformatted with different line break and indentations.

This makes reviewing extremely difficult.

Comment (norbusan) [reply src/pretix/eventyay_common/templates/eventyay_common/dashboard/dashboard.html]: This applies to the follow-up code, too.

I will not go over the whole one character at a time and check whether this is a pure reformatting issue or whether there have been code changes.

Please set up your editor/IDE to *NOT* change the formatting.

**Review by norbusan — CHANGES_REQUESTED** [review]

File: src/pretix/base/orderimport.py (hunk 2 above)
Comment (suhailnadaf509) [reply src/pretix/base/orderimport.py]: Noted, thanks for the fix!

File: src/pretix/eventyay_common/templates/eventyay_common/dashboard/dashboard.html (hunk 3 above)
Comment (suhailnadaf509) [reply src/pretix/eventyay_common/templates/eventyay_common/dashboard/dashboard.html]: Understood , I’ll preserve original formatting moving forward

**Review by norbusan — APPROVED** [review]
LGTM
