### PR TITLE
fix: dropdown event search redirects to unified dashboard instead of tickets dashboard

### LINKED ISSUE #1117: Bug: Dropdown Event Search Redirects to Ticketing Dashboard Instead of Event Dashboard
In the **common dashboard**, the **event search dropdown** correctly lists available events.
However, when a user clicks on an event from the dropdown, they are redirected to the **ticketing dashboard** instead of the **main event dashboard** for that event.

The expected behavior is that selecting an event should open the **specific unified event dashboard**, not a component-specific (Tickets) view.

### 🧩 Steps to Reproduce

1. Log in to the organizer dashboard.
2. Use the **event search dropdown** in the common dashboard header.
3. Select any event from the dropdown list.

**Current Result:**
User is redirected to the **Tickets dashboard** for the selected event.

**Expected Result:**
User should be redirected to the **main unified event dashboard** of that event (showing overview, settings, and component links).

---

### ✅ Requirements

* [ ] Update dropdown event selection links to point to the unified event dashboard path (e.g. `/tickets/common/event/{org}/{event}/dashboard` → `/common/event/{org}/{event}/`).
* [ ] Ensure consistent behavior across all roles (organizer, admin, co-organizer).
* [ ] Test that search and navigation still function smoothly after the update.

Image

### PR DESCRIPTION
**Pull request by ArnavBallinCode**
fixes #1117 : redirect event dropdown to unified dashboard instead of tickets dashboard

- Update serialize_event() in typeahead.py to use eventyay_common:event.index
- Update presale organizer area link to point to unified dashboard
- Ensures consistent navigation behavior across all user roles (organizer, admin, co-organizer)
- Fixes issue where event search dropdown redirected to tickets dashboard instead of main event dashboard

## Summary by Sourcery

Unify event dropdown navigation across user roles to point to the main event dashboard instead of the tickets dashboard and clean up UI styling

Bug Fixes:
- Redirect event search dropdown to the unified event dashboard by updating serialize_event URL
- Fix presale organizer area link to use the unified dashboard path

Enhancements:
- Remove box-shadow styling from the AppBar component for a cleaner UI appearance

### CODE REVIEW

**Comment by ArnavBallinCode** [comment]
https://github.com/user-attachments/assets/99df4ae7-f622-4714-8c61-ce424c6f10a6

**Comment by hongquan** [comment]
The PR title should be a meaningful sentence, not "Fix/xxx", "Feature/xxxx".

File: app/eventyay/static/pretixpresale/js/ui/popover.js [hunk 1]
```diff
@@ -121,7 +121,7 @@ $(function () {
   if (showOrganizerArea) {
     blocks.push(
       `<div class="profile-menu organizer-area">
-          <a href="${basePath}/control/event/${organizerName}/${eventSlug}" target="_self" class="btn btn-outline-success">
+          <a href="${basePath}/common/event/${organizerName}/${eventSlug}" target="_self" class="btn btn-outline-success">
```
Comment (Gagan-Ram) [inline app/eventyay/static/pretixpresale/js/ui/popover.js]: This change is not required.

Comment (ArnavBallinCode) [reply app/eventyay/static/pretixpresale/js/ui/popover.js]: Makes sense, reverted this change..

**Comment by Gagan-Ram** [comment]
@ArnavBallinCode Please make change in the typeahed.py file only.
The current code makes changes to public page of event. (changes link of 'organizer area') which is not asked in the issue.

**Comment by ArnavBallinCode** [comment]
Screenshot 2025-11-02 at 2 44 16 AM
isnt that the only file changed?
